# Generated by Django 5.1.2 on 2024-10-31 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_alter_mission_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='mission.mission'),
        ),
    ]
